/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Alex Bastías
 * Created: 26-02-2018
 */

-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 12:26:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsihve
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsihve
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsihve` DEFAULT CHARACTER SET utf8 ;
USE `dbsihve` ;

-- -----------------------------------------------------
-- Table `dbsihve`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsihve`.`actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equipo_id` INT NULL,
  `tipoEquipo_id` INT NULL,
  `responsable_id` INT NULL,
  `fechaInicio` DATETIME NULL,
  `fechaTermino` DATETIME NULL,
  `enSistema` INT NULL DEFAULT 1,
  `ubicacion_id` INT NULL,
  `descripcionActividad` VARCHAR(45) NULL,
  `estadoActividad_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsihve`.`componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsihve`.`componentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsihve`.`revisionesComponentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsihve`.`revisionesComponentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `actividad_id` INT NOT NULL,
  `componente_id` INT NOT NULL,
  `estado_id` INT NULL,
  `serial` VARCHAR(45) NULL,
  `seteo` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_componente_id_idx` (`componente_id` ASC),
  INDEX `fk_actividad_id_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_componente_id`
    FOREIGN KEY (`componente_id`)
    REFERENCES `dbsihve`.`componentes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_id`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `dbsihve`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsihve`.`enumTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsihve`.`enumTable` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsihve`.`equipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsihve`.`equipos` (
  `id` INT NOT NULL,
  `tipoEquipo_id` INT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

